version: '3'
services:
  frontend:
    image: node:16-alpine
    working_dir: /frontend
    volumes:
      - .:/frontend
    command: sh -c "npm install && npm run build:no-eslint"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
