version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - "3000"
    restart: always
    command: ["npm", "run", "dev"]  

  deploy:
    image: ecm-fe  
    volumes:
      - /var/www/html:/app/dist 
    command: ["sh", "-c", "cp -r /app/dist/* /var/www/html/"]  
