version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - "3000"
    restart: always

networks:
  ecommerce-net:
    driver: bridge
