version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /frontend
    volumes:
      - .:/frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - frontend
